/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-06-29 06:29:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Footer Section Start -->\r\n");
      out.write("	<footer class=\"footer-area pt-100 pb-70\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("					<div class=\"footer-widget\">\r\n");
      out.write("						<div class=\"footer-logo\">\r\n");
      out.write("							<a href=\"index.jsp\">\r\n");
      out.write("								<img src=\"assets/img/logo.png\" alt=\"logo\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<p>Siamaq Consultancy Pvt. Ltd. is a fastest creating web progression association arranged in pune, India. \r\n");
      out.write("						Siamaq System Creates Bright and Functional Website Design for Businesses and Individuals.</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"footer-social\">\r\n");
      out.write("							<a href=\"#\" target=\"_blank\"><i class='bx bxl-facebook'></i></a>\r\n");
      out.write("							<a href=\"#\" target=\"_blank\"><i class='bx bxl-twitter'></i></a>\r\n");
      out.write("							<a href=\"#\" target=\"_blank\"><i class='bx bxl-pinterest-alt'></i></a>\r\n");
      out.write("							<a href=\"#\" target=\"_blank\"><i class='bx bxl-linkedin'></i></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("					<div class=\"footer-widget pl-60\">\r\n");
      out.write("						<h3>For Candidate</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"find-job.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Browse Jobs\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"account.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Account\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"post-job.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Post a Job\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"contact.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Contact\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<!-- <li>\r\n");
      out.write("								<a href=\"resume.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Resume\r\n");
      out.write("								</a>\r\n");
      out.write("							</li> -->\r\n");
      out.write("							<!--<li>\r\n");
      out.write("								<a href=\"job-list.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Job List\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>-->\r\n");
      out.write("							<!-- <li>\r\n");
      out.write("								<a href=\"sign-up.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Sign Up\r\n");
      out.write("								</a>\r\n");
      out.write("							</li> -->\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("					<div class=\"footer-widget pl-60\">\r\n");
      out.write("						<h3>Quick Links</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"index.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Home\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"about.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									About\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"faq.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									FAQ\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<!--<li>\r\n");
      out.write("									<a href=\"pricing.jsp\">\r\n");
      out.write("										<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("										Pricing\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>-->\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"privacy.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Privacy\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"terms-condition.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Conditions\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<!-- <li>\r\n");
      out.write("								<a href=\"contact.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Contact\r\n");
      out.write("								</a>\r\n");
      out.write("							</li> -->\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("					<div class=\"footer-widget footer-info\">\r\n");
      out.write("						<h3>Information</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>\r\n");
      out.write("								<span>\r\n");
      out.write("									<i class='bx bxs-phone'></i>\r\n");
      out.write("									Phone:\r\n");
      out.write("								</span>\r\n");
      out.write("								<a href=\"tel:882569756\">\r\n");
      out.write("									+91 7249763489\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li>\r\n");
      out.write("								<span>\r\n");
      out.write("									<i class='bx bxs-envelope'></i>\r\n");
      out.write("									Email:\r\n");
      out.write("								</span>\r\n");
      out.write("								<a href=\"mailto:info@jovie.com\">\r\n");
      out.write("									info@siamaqsystem.com\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li>\r\n");
      out.write("								<span>\r\n");
      out.write("									<i class='bx bx-location-plus'></i>\r\n");
      out.write("									Address:\r\n");
      out.write("								</span>\r\n");
      out.write("								R.H. N0 : 15, Ujjwal Regalia Society, <br>\r\n");
      out.write("								Baner, Pune, Maharashtra - 411045.\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<div class=\"copyright-text text-center\">\r\n");
      out.write("		<p>Siamaq Consultancy Pvt. Ltd. © 2021 All rights reserved.</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Footer Section End -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
