/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-06-05 04:59:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_002dabout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Owl Carousel CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("<!-- Owl Carousel Theme Default CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/owl.theme.default.min.css\">\r\n");
      out.write("<!-- Box Icon CSS-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/boxicon.min.css\">\r\n");
      out.write("<!-- Flaticon CSS-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/fonts/flaticon/flaticon.css\">\r\n");
      out.write("<!-- Magnific CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("<!-- Meanmenu CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/meanmenu.css\">\r\n");
      out.write("<!-- Nice Select CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/nice-select.css\">\r\n");
      out.write("<!-- Style CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("<!-- Dark CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/dark.css\">\r\n");
      out.write("<!-- Responsive CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/responsive.css\">\r\n");
      out.write("<!-- Title CSS -->\r\n");
      out.write("<title>Siamaq Portal</title>\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"assets/img/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "loginHeader.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- Page Title Start -->\r\n");
      out.write("	<section class=\"page-title title-bg1\" style=\"background-image: url(assets/img/title-bg/1.png)\">\r\n");
      out.write("		<div class=\"d-table\">\r\n");
      out.write("			<div class=\"d-table-cell\">\r\n");
      out.write("				<h2>About Us</h2>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("					<li>About Us</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"lines\">\r\n");
      out.write("			<div class=\"line\"></div>\r\n");
      out.write("			<div class=\"line\"></div>\r\n");
      out.write("			<div class=\"line\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- Page Title End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- About Section Start -->\r\n");
      out.write("	<section class=\"about-section ptb-100\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center\">\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div class=\"about-text\">\r\n");
      out.write("						<div class=\"section-title\">\r\n");
      out.write("							<h4>Welcome to</h4>\r\n");
      out.write("							<h1>Siamaq Consultancy Pvt. Ltd.</h1>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<p>Siamaq started its brand building journey in the year 2019\r\n");
      out.write("							. Our journey has been full of ups & downs, but we've overcome\r\n");
      out.write("							every huddle in our way with our sheer determination to deliver\r\n");
      out.write("							on our promises.</p>\r\n");
      out.write("\r\n");
      out.write("						<p>Siamaq Consultancy was started with small determined team\r\n");
      out.write("							of 03 and over the years we've grown from a team to a family of\r\n");
      out.write("							50. We have mastered our skill set in all the domains and pioneer\r\n");
      out.write("							in delivering measurable results to our clientele.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div class=\"about-img\">\r\n");
      out.write("						<img src=\"assets/img/abou.png\" alt=\"about image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- About Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Way To Use Section Start -->\r\n");
      out.write("	<!-- <section class=\"use-section pt-100 pb-70\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"section-title text-center\">\r\n");
      out.write("					<h2>Easiest Way To Use</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("						<div class=\"use-text\">\r\n");
      out.write("							<span>1</span>\r\n");
      out.write("							<i class='flaticon-website'></i>\r\n");
      out.write("							<h3>Browse Job</h3>\r\n");
      out.write("							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("						<div class=\"use-text\">\r\n");
      out.write("							<span>2</span>\r\n");
      out.write("							<i class='flaticon-recruitment'></i>\r\n");
      out.write("							<h3>Find Your Vaccancy</h3>\r\n");
      out.write("							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-4 col-sm-6 offset-sm-3 offset-lg-0\">\r\n");
      out.write("						<div class=\"use-text\">\r\n");
      out.write("							<span>3</span>\r\n");
      out.write("							<i class='flaticon-login'></i>\r\n");
      out.write("							<h3>Submit Resume</h3>\r\n");
      out.write("							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section> -->\r\n");
      out.write("	<!-- Way To Use Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- <!-- Why Choose Section Start\r\n");
      out.write("        <section class=\"why-choose-two pt-100 pb-70\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"section-title text-center\">\r\n");
      out.write("                    <h2>Why You Choose Us Among Other Job Site?</h2>\r\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"choose-card\">\r\n");
      out.write("                            <i class=\"flaticon-resume\"></i>\r\n");
      out.write("                            <h3>Advertise Job</h3>\r\n");
      out.write("                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore   </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"choose-card\">\r\n");
      out.write("                            <i class=\"flaticon-recruitment\"></i>\r\n");
      out.write("                            <h3>Recruiter Profiles</h3>\r\n");
      out.write("                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore   </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-4 col-sm-6 offset-sm-3 offset-lg-0\">\r\n");
      out.write("                        <div class=\"choose-card\">\r\n");
      out.write("                            <i class=\"flaticon-employee\"></i>\r\n");
      out.write("                            <h3>Find Your Dream Job</h3>\r\n");
      out.write("                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore   </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section> -->\r\n");
      out.write("	<!--  Why Choose Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Grow Business Section Start -->\r\n");
      out.write("	<div class=\"grow-business pb-100\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center\">\r\n");
      out.write("				<div class=\"col-lg-5\">\r\n");
      out.write("					<div class=\"grow-img\">\r\n");
      out.write("						<img src=\"assets/img/grow-img1.png\" alt=\"grow image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-7\">\r\n");
      out.write("					<div class=\"grow-text\">\r\n");
      out.write("						<div class=\"section-title\">\r\n");
      out.write("							<h3>CTO / Co-Founder Director</h3>\r\n");
      out.write("							<h2>Mr. Arvind Bharadwaj</h2>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<p>Mr. Arvind Bharadwaj was born at Jaunpur , a small\r\n");
      out.write("							village/town located near Varanasi. As a young boy he was always\r\n");
      out.write("							keen in analytical subjects such as Mathematics & Sciences. He\r\n");
      out.write("							then pursued his Masters at Delhi in the field of Electronic &\r\n");
      out.write("							Computer science.</p>\r\n");
      out.write("\r\n");
      out.write("						<p>Early days of his career Mr. Arvind taught young aspirants\r\n");
      out.write("							at TVBSHS, GIT(Gurgaon Institute of Technology),VKM. He preferred\r\n");
      out.write("							teaching as he was interested in communicating ideas with his\r\n");
      out.write("							fellow peers. However he wasnât satisfied with teaching and\r\n");
      out.write("							decided to branch out on his entrepreneurial journey and thus\r\n");
      out.write("							Siamaq Consultancy was born.</p>\r\n");
      out.write("\r\n");
      out.write("						<!-- <div class=\"theme-btn\">\r\n");
      out.write("                                <a href=\"#\" class=\"default-btn\">Checkout More</a>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"grow-business pb-100\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-7\">\r\n");
      out.write("					<div class=\"grow-text\">\r\n");
      out.write("						<div class=\"section-title\">\r\n");
      out.write("							<h3>Co-Founder Director</h3>\r\n");
      out.write("							<h2>Ms. Shreya Shri</h2>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<p>Born in Kolkata , Miss Shreya is a true Bengali at heart.\r\n");
      out.write("							During her formative year she always believed in pushing the\r\n");
      out.write("							boundaries in every challenge she took on. Her Alma matter\r\n");
      out.write("							includes (RCEW), she has completed B.Tech in computer science.</p>\r\n");
      out.write("\r\n");
      out.write("						<p>Her career spans of over 09 years on experience , with\r\n");
      out.write("							brand names like Electronic Arts under her belt. Her personality\r\n");
      out.write("							is outspoken and this trait ventured her career path towards\r\n");
      out.write("							entrepreneurship with Siamaq Consultancy. Strong, brave women has\r\n");
      out.write("							never let anybody influence the decision making and always\r\n");
      out.write("							followed what her heart says.</p>\r\n");
      out.write("\r\n");
      out.write("						<!-- <div class=\"theme-btn\">\r\n");
      out.write("                                <a href=\"#\" class=\"default-btn\">Checkout More</a>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-5\">\r\n");
      out.write("					<div class=\"grow-img\">\r\n");
      out.write("						<img src=\"assets/img/grow-img2.png\" alt=\"grow image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Grow Business Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Counter Section Start -->\r\n");
      out.write("	<!-- <div class=\"counter-section pt-100 pb-70\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row counter-area\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-6\">\r\n");
      out.write("                        <div class=\"counter-text\">\r\n");
      out.write("                            <i class=\"flaticon-resume\"></i>\r\n");
      out.write("                            <h2><span>1225</span></h2>\r\n");
      out.write("                            <p>Job Posted</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("        \r\n");
      out.write("                    <div class=\"col-lg-3 col-6\">\r\n");
      out.write("                        <div class=\"counter-text\">\r\n");
      out.write("                            <i class=\"flaticon-recruitment\"></i>\r\n");
      out.write("                            <h2><span>145</span></h2>\r\n");
      out.write("                            <p>Job Filed</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("        \r\n");
      out.write("                    <div class=\"col-lg-3 col-6\">\r\n");
      out.write("                        <div class=\"counter-text\">\r\n");
      out.write("                            <i class=\"flaticon-portfolio\"></i>\r\n");
      out.write("                            <h2><span>170</span></h2>\r\n");
      out.write("                            <p>Company</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("        \r\n");
      out.write("                    <div class=\"col-lg-3 col-6\">\r\n");
      out.write("                        <div class=\"counter-text\">\r\n");
      out.write("                            <i class=\"flaticon-employee\"></i>\r\n");
      out.write("                            <h2><span>125</span></h2>\r\n");
      out.write("                            <p>Members</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("         -->\r\n");
      out.write("	<!-- Counter Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Testimonial Section Start -->\r\n");
      out.write("	<div class=\"testimonial-style-two ptb-100\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"section-title text-center\">\r\n");
      out.write("				<h2>What Client Say About Us</h2>\r\n");
      out.write("				<p>Create world class digital presence with Siamaq consultancy.\r\n");
      out.write("					We are integrated marketing communication agency with capabilities\r\n");
      out.write("					and experience to grow and enhance your business both locally and\r\n");
      out.write("					globally.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"testimonial-slider-two owl-carousel owl-theme\">\r\n");
      out.write("					<div class=\"testimonial-items\">\r\n");
      out.write("						<div class=\"testimonial-text\">\r\n");
      out.write("							<i class='flaticon-left-quotes-sign'></i>\r\n");
      out.write("							<p>Working with Siamamq Consultancy Pvt. Ltd. was a\r\n");
      out.write("								game-changer for our business. Their strategic guidance and\r\n");
      out.write("								expert advice helped us streamline our operations and achieve\r\n");
      out.write("								significant growth. Their team is highly knowledgeable,\r\n");
      out.write("								responsive, and dedicated to delivering exceptional results. We\r\n");
      out.write("								highly recommend Siamamq Consultancy Pvt. Ltd. to any\r\n");
      out.write("								organization looking to elevate their business to the next\r\n");
      out.write("								level.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"testimonial-info-text\">\r\n");
      out.write("							<h3>Alisa Meair</h3>\r\n");
      out.write("							<p>CEO of Company</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"testimonial-items\">\r\n");
      out.write("						<div class=\"testimonial-text\">\r\n");
      out.write("							<i class='flaticon-left-quotes-sign'></i>\r\n");
      out.write("							<p>Siamamq Consultancy exceeded our expectations in every\r\n");
      out.write("								way. Their attention to detail, professionalism, and commitment\r\n");
      out.write("								to delivering high-quality results were exceptional. Their\r\n");
      out.write("								ability to analyze complex problems and provide practical\r\n");
      out.write("								solutions was truly impressive. We are grateful for the positive\r\n");
      out.write("								impact Siamamq Consultancy had on our business and would not\r\n");
      out.write("								hesitate to recommend their services to others.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"testimonial-info-text\">\r\n");
      out.write("							<h3>Matty Brownell</h3>\r\n");
      out.write("							<p>Web Developer</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"testimonial-items\">\r\n");
      out.write("						<div class=\"testimonial-text\">\r\n");
      out.write("							<i class='flaticon-left-quotes-sign'></i>\r\n");
      out.write("							<p>Choosing Siamamq Consultancy was one of the best decisions\r\n");
      out.write("								we made for our company. Their strategic insights and\r\n");
      out.write("								personalized approach helped us overcome obstacles and achieve\r\n");
      out.write("								remarkable success. Siamamq Consultancy's team not only provided\r\n");
      out.write("								expert guidance but also became trusted advisors who genuinely\r\n");
      out.write("								cared about our business's growth. We highly recommend their\r\n");
      out.write("								services to anyone seeking exceptional consultancy services.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"testimonial-info-text\">\r\n");
      out.write("							<h3>Kristen Walters</h3>\r\n");
      out.write("							<p>Graphics Designer</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Testimonial Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Blog Section Start -->\r\n");
      out.write("	<section class=\"blog-section pt-100 pb-70\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"section-title text-center\">\r\n");
      out.write("				<h2>News, Tips & Articles</h2>\r\n");
      out.write("				<p>Benefit from expert career advice from seasoned professionals in the IT field. \r\n");
      out.write("				Siamaq  Portal regularly shares tips on resume building, interview preparation, \r\n");
      out.write("				and career growth strategies specific to the IT industry.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("					<div class=\"blog-card\">\r\n");
      out.write("						<div class=\"blog-img\">\r\n");
      out.write("							<a href=\"https://medium.com/@Siamaq/website-designs-that-are-innovative-unique-e9856fe4aee4\">\r\n");
      out.write("								<img src=\"assets/img/blog/1.png\" alt=\"blog image\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"blog-text\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>\r\n");
      out.write("									<i class='bx bxs-user'></i>\r\n");
      out.write("									Admin\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<i class='bx bx-calendar'></i>\r\n");
      out.write("									3 Nov, 2022\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("\r\n");
      out.write("							<h3>\r\n");
      out.write("								<a href=\"https://medium.com/@Siamaq/website-designs-that-are-innovative-unique-e9856fe4aee4\">\r\n");
      out.write("									How to Indroduce in Yourself in Job Interview?\r\n");
      out.write("								</a>\r\n");
      out.write("							</h3>\r\n");
      out.write("							<p> Introduce yourself by stating your name and providing a brief overview of your professional background, \r\n");
      out.write("								including your education, work experience, and any relevant skills or certifications.</p>\r\n");
      out.write("\r\n");
      out.write("							<a href=\"https://medium.com/@Siamaq/website-designs-that-are-innovative-unique-e9856fe4aee4\" class=\"blog-btn\">\r\n");
      out.write("								Read More\r\n");
      out.write("								<i class='bx bx-plus bx-spin'></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("					<div class=\"blog-card\">\r\n");
      out.write("						<div class=\"blog-img\">\r\n");
      out.write("							<a href=\"https://medium.com/@07rajabhi/why-you-should-consider-seo-for-your-website-e19c34246023\">\r\n");
      out.write("								<img src=\"assets/img/blog/2.png\" alt=\"blog image\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"blog-text\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>\r\n");
      out.write("									<i class='bx bxs-user'></i>\r\n");
      out.write("									Admin\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<i class='bx bx-calendar'></i>\r\n");
      out.write("									3 Nov, 2022\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("\r\n");
      out.write("							<h3>\r\n");
      out.write("								<a href=\"https://medium.com/@Siamaq/why-you-should-consider-seo-for-your-website-e19c34246023\">\r\n");
      out.write("									10 Things You Should Know Before Apply\r\n");
      out.write("								</a>\r\n");
      out.write("							</h3>\r\n");
      out.write("							<p> It is important to carefully read job description to ensure that you meet requirements and have the necessary skills and experience. \r\n");
      out.write("								Understanding the company culture and values can help you determine if it is a good fit for you.</p>\r\n");
      out.write("\r\n");
      out.write("							<a href=\"https://medium.com/@Siamaq/why-you-should-consider-seo-for-your-website-e19c34246023\" class=\"blog-btn\">\r\n");
      out.write("								Read More\r\n");
      out.write("								<i class='bx bx-plus bx-spin'></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-4 col-sm-6 offset-sm-3 offset-lg-0\">\r\n");
      out.write("					<div class=\"blog-card\">\r\n");
      out.write("						<div class=\"blog-img\">\r\n");
      out.write("							<a href=\"https://medium.com/@Siamaq/why-you-should-consider-seo-for-your-website-e19c34246023\">\r\n");
      out.write("								<img src=\"assets/img/blog/3.png\" alt=\"blog image\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"blog-text\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>\r\n");
      out.write("									<i class='bx bxs-user'></i>\r\n");
      out.write("									Admin\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<i class='bx bx-calendar'></i>\r\n");
      out.write("									3 Nov, 2022\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("\r\n");
      out.write("							<h3>\r\n");
      out.write("								<a href=\"https://www.siamaqsystem.com/digital-business-cards-networking-solution-of-2022-digital-business-card-agency/index.jsp\">\r\n");
      out.write("									The Reason Why Software Develope is the Best Job\r\n");
      out.write("								</a>\r\n");
      out.write("							</h3>\r\n");
      out.write("							<p>There are several reasons why software development is considered one of the best jobs in the modern workforce. software development provides a great level of flexibility and autonomy. \r\n");
      out.write("								</p>\r\n");
      out.write("\r\n");
      out.write("							<a href=\"https://www.siamaqsystem.com/digital-business-cards-networking-solution-of-2022-digital-business-card-agency/index.jsp\" class=\"blog-btn\">\r\n");
      out.write("								Read More\r\n");
      out.write("								<i class='bx bx-plus bx-spin'></i>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- Blog Section End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer Section Start -->\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- <footer class=\"footer-area pt-100 pb-70\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("					<div class=\"footer-widget\">\r\n");
      out.write("						<div class=\"footer-logo\">\r\n");
      out.write("							<a href=\"index.jsp\"> <img src=\"assets/img/logo.png\"\r\n");
      out.write("								alt=\"logo\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<p>Siamaq Consultancy Pvt. Ltd. is a fastest creating web\r\n");
      out.write("							progression association arranged in pune, India. Siamaq System\r\n");
      out.write("							Creates Bright and Functional Website Design for Businesses and\r\n");
      out.write("							Individuals.</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"footer-social\">\r\n");
      out.write("							<a href=\"#\" target=\"_blank\"><i class='bx bxl-facebook'></i></a> <a\r\n");
      out.write("								href=\"#\" target=\"_blank\"><i class='bx bxl-twitter'></i></a> <a\r\n");
      out.write("								href=\"#\" target=\"_blank\"><i class='bx bxl-pinterest-alt'></i></a>\r\n");
      out.write("							<a href=\"#\" target=\"_blank\"><i class='bx bxl-linkedin'></i></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("					<div class=\"footer-widget pl-60\">\r\n");
      out.write("						<h3>For Candidate</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"find-job.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> Browse Jobs\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"account.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> Account\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"post-job.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> Post a Job\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"resume.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> Resume\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"job-list.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Job List\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"sign-up.jsp\">\r\n");
      out.write("									<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("									Sign Up\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("					<div class=\"footer-widget pl-60\">\r\n");
      out.write("						<h3>Quick Links</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"index.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> Home\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"about.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> About\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"faq.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> FAQ\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li>\r\n");
      out.write("									<a href=\"pricing.jsp\">\r\n");
      out.write("										<i class='bx bx-chevrons-right bx-tada'></i>\r\n");
      out.write("										Pricing\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("							<li><a href=\"privacy.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> Privacy\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"terms-condition.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> Conditions\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"contact.jsp\"> <i\r\n");
      out.write("									class='bx bx-chevrons-right bx-tada'></i> Contact\r\n");
      out.write("							</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("					<div class=\"footer-widget footer-info\">\r\n");
      out.write("						<h3>Information</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><span> <i class='bx bxs-phone'></i> Phone:\r\n");
      out.write("							</span> <a href=\"tel:882569756\"> +91 7249763489 </a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><span> <i class='bx bxs-envelope'></i> Email:\r\n");
      out.write("							</span> <a href=\"mailto:info@jovie.com\"> info@siamaqsystem.com </a></li>\r\n");
      out.write("\r\n");
      out.write("							<li><span> <i class='bx bx-location-plus'></i>\r\n");
      out.write("									Address:\r\n");
      out.write("							</span> R.H. N0 : 15, Ujjwal Regalia Society, <br> Baner, Pune,\r\n");
      out.write("								Maharashtra - 411045.</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<div class=\"copyright-text text-center\">\r\n");
      out.write("		<p>\r\n");
      out.write("			Â© Jovie is Proudly Owned by <a href=\"https://hibootstrap.com/\"\r\n");
      out.write("				target=\"_blank\">HiBootstrp</a>\r\n");
      out.write("		</p>\r\n");
      out.write("	</div>\r\n");
      out.write(" -->	<!-- Footer Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Back To Top Start -->\r\n");
      out.write("	<div class=\"top-btn\">\r\n");
      out.write("		<i class='bx bx-chevrons-up bx-fade-up'></i>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Back To Top End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- jQuery first, then Bootstrap JS -->\r\n");
      out.write("	<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- Owl Carousel JS -->\r\n");
      out.write("	<script src=\"assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<!-- Nice Select JS -->\r\n");
      out.write("	<script src=\"assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<!-- Magnific Popup JS -->\r\n");
      out.write("	<script src=\"assets/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<!-- Subscriber Form JS -->\r\n");
      out.write("	<script src=\"assets/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("	<!-- Form Velidation JS -->\r\n");
      out.write("	<script src=\"assets/js/form-validator.min.js\"></script>\r\n");
      out.write("	<!-- Contact Form -->\r\n");
      out.write("	<script src=\"assets/js/contact-form-script.js\"></script>\r\n");
      out.write("	<!-- Meanmenu JS -->\r\n");
      out.write("	<script src=\"assets/js/meanmenu.js\"></script>\r\n");
      out.write("	<!-- Custom JS -->\r\n");
      out.write("	<script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
